before:
  hooks:
    - go mod tidy
    - go test -race
    - ./test.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    image_templates:
    - "docker.pkg.github.com/cwbooth5/go2redirector/go2redirector:{{ .Tag }}"
    extra_files:
    - main.go
    - go.mod
    - go.sum
    - godb.json.init
    - install.sh
    - api/
    - http/
    - core/
    - static/
    - templates/
    - tools/
    - README.md
